(()=>{const $=id=>document.getElementById(id);const S={room:null,role:null,tokenId:localStorage.getItem("cordds_token")||"",roomName:""};$("tokenId").value=S.tokenId;
function setStatus(t){$("status").textContent=t}
function identity(p){return p+"-"+Math.random().toString(36).slice(2,10)}
function tokenSource(){if(!S.tokenId)throw Error("Save the LiveKit Development Token Server ID first.");if(!window.LivekitClient)throw Error("LiveKit SDK did not load.");return LivekitClient.TokenSource.developmentTokenServer(S.tokenId)}
function showApp(role){$("gate").hidden=true;$("app").hidden=false;S.role=role;$("operatorPanel").hidden=role!=="operator";$("cameraPanel").hidden=role!=="camera";setStatus(role.toUpperCase())}
async function connect(roomName,role){const L=LivekitClient;const source=tokenSource();S.room=new L.Room({adaptiveStream:true,dynacast:true});S.roomName=roomName;S.room.on(L.RoomEvent.TrackSubscribed,(track,publication,participant)=>{if(role!=="operator"||track.kind!=="video")return;const el=track.attach();const card=document.createElement("div");card.className="cam";card.innerHTML='<div class="meta"><b>Camera</b> <span class="online">● ONLINE</span></div>';card.prepend(el);$("remoteArea").appendChild(card);});S.room.on(L.RoomEvent.TrackUnsubscribed,(track)=>track.detach());S.room.on(L.RoomEvent.Disconnected,()=>{setStatus("OFFLINE");$("roomState").textContent="DISCONNECTED"});const r=await source.fetch({roomName,participantIdentity:identity(role),participantName:role==="operator"?"Operator":"Camera"});if(!r?.serverUrl||!r?.participantToken)throw Error("LiveKit returned incomplete connection details.");await S.room.connect(r.serverUrl,r.participantToken);$("roomState").textContent=roomName+" · CONNECTED";setStatus(role==="operator"?"OPERATOR ONLINE":"CAMERA ONLINE")}
$("saveToken").onclick=()=>{S.tokenId=$("tokenId").value.trim();localStorage.setItem("cordds_token",S.tokenId);$("gateMsg").textContent=S.tokenId?"Saved.":"Enter the Development Token Server ID."};
$("operatorBtn").onclick=async()=>{try{showApp("operator");const n=$("room").value.trim()||("cb-"+Math.random().toString(36).slice(2,7));$("room").value=n;await connect(n,"operator")}catch(e){$("gate").hidden=false;$("app").hidden=true;$("gateMsg").textContent=e.message;setStatus("ERROR")}};
$("createRoom").onclick=async()=>{try{if(S.room)await S.room.disconnect();$("remoteArea").innerHTML="";await connect($("room").value.trim()||("cb-"+Math.random().toString(36).slice(2,7)),"operator")}catch(e){$("roomState").textContent="ERROR";$("status").textContent="ERROR";alert(e.message)}};
$("cameraBtn").onclick=()=>showApp("camera");
$("startCamera").onclick=async()=>{const n=$("cameraRoom").value.trim();if(!n){$("cameraMsg").textContent="Enter the operator room ID.";return}let stream;try{$("cameraMsg").textContent="Requesting camera permission…";stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"},width:{ideal:1280},height:{ideal:720}},audio:false});$("localVideo").srcObject=stream;$("cameraMsg").textContent="Camera granted. Connecting…";await connect(n,"camera");const track=new LivekitClient.LocalVideoTrack(stream.getVideoTracks()[0]);await S.room.localParticipant.publishTrack(track,{name:"security-camera"});$("cameraMsg").textContent="Camera is LIVE. Keep this page open."}catch(e){if(stream)stream.getTracks().forEach(t=>t.stop());$("cameraMsg").textContent="Camera error: "+(e.message||e.name);setStatus("ERROR")}};
$("leave").onclick=async()=>{try{if(S.room)await S.room.disconnect()}catch(e){}location.reload()};})();